version: '4'
services:
  db:
      image: 'postgres:latest'
      restart: 'always'
      environment:
        - POSTGRES_USER: postgres
        - POSTGRES_PASSWORD: 945332002Af*
      logging: 
        options: 
            max-size: 10m
            max-file: "3"
      ports:
        - 5435:5432
      volumes:
        - ./pgdata:/var/lib/postgresql/data
        - ./create-db.sql:/docker-entrypoin-initdb.d/create_database.sql
